from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

# Configuration de la connexion à la base de données MySQL
db_username = 'root'
db_password = ''
db_host = 'localhost'
db_port = '3306'
db_name = 'projet_sae'

# Créez un moteur SQLAlchemy
engine = create_engine(f'mysql+mysqlconnector://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}')

# Créez une session SQLAlchemy
Session = sessionmaker(bind=engine)
session = Session()

# Liste des noms de séries
noms_series = [
    "24",
    "90210",
    "Alias",
    "Angel",
    "Battlestar Galactica",
    "Better Off Ted",
    "Bionic Woman",
    "Blade",
    "Blood Ties",
    "Bones",
    "Breaking Bad",
    "Buffy",
    "Burn Notice",
    "Californication",
    "Caprica",
    "Charmed",
    "Chuck",
    "Cold Case",
    "Community",
    "Criminal Minds",
    "Cupid",
    "Day Break",
    "Demons",
    "Desperate Housewives",
    "Dexter",
    "Dirty Sexy Money",
    "Dirt",
    "Doctor Who",
    "Dollhouse",
    "Eleventh Hour",
    "Entourage",
    "Eureka",
    "Extras",
    "Fear Itself",
    "FlashForward",
    "Flashpoint",
    "Flight of the Conchords",
    "Friday Night Lights",
    "Friends",
    "Fringe",
    "Futurama",
    "Gary Unmarried",
    "Ghost Whisperer",
    "Gossip Girl",
    "Greek",
    "Grey's Anatomy",
    "Heroes",
    "House",
    "How I Met Your Mother",
    "In Treatment",
    "Invasion",
    "Jake 2.0",
    "Jekyll",
    "Jericho",
    "John from Cincinnati",
    "Knight Rider",
    "Kyle XY",
    "Legend of the Seeker",
    "Leverage",
    "Lie to Me",
    "Life",
    "Lost",
    "Mad Men",
    "Masters of SciFi",
    "Medium",
    "Melrose Place",
    "Mental",
    "Merlin",
    "Moonlight",
    "My Name Is Earl",
    "NCIS: Los Angeles",
    "NCIS",
    "Nip/Tuck",
    "One Tree Hill",
    "Oz",
    "Painkiller Jane",
    "Primeval",
    "Prison Break",
    "Private Practice",
    "Psych",
    "Pushing Daisies",
    "Raines",
    "Reaper",
    "Robin Hood",
    "Samantha Who?",
    "Sanctuary",
    "Scrubs",
    "Sex and the City",
    "Six Feet Under",
    "Skins",
    "Smallville",
    "Sons of Anarchy",
    "South Park",
    "Spaced",
    "Stargate Atlantis",
    "Stargate SG-1",
    "Stargate Universe",
    "Supernatural",
    "Swingtown",
    "The 4400",
    "The Big Bang Theory",
    "The Black Donnellys",
    "The Kill Point",
    "The Lost Room",
    "The Mentalist",
    "The Nine",
    "The OC",
    "The Pretender",
    "The Riches",
    "The Sarah Connor Chronicles",
    "The Shield",
    "The Sopranos",
    "The Tudors",
    "The Vampire Diaries",
    "The Wire",
    "Torchwood",
    "Traveler",
    "Tru Calling",
    "True Blood",
    "Ugly Betty",
    "Veronica Mars",
    "V",
    "Weeds",
    "Whitechapel",
    "Women's Murder Club",
    "The X-Files",
    "Rome"
]

# Liste des descriptions de séries
descriptions = [
    "24 heures pour sauver le monde. L'agent Jack Bauer doit faire face à des menaces terroristes et des complots dans cette série d'action en temps réel.",
    "Suivez la vie de plusieurs adolescents riches à Beverly Hills dans cette série dramatique.",
    "Une espionne de la CIA, Sydney Bristow, mène une double vie et s'efforce de découvrir la vérité sur son passé.",
    "Un vampire avec une âme, Angel, lutte contre les forces du mal à Los Angeles.",
    "L'humanité est au bord de l'extinction et doit lutter pour survivre contre les Cylons, des robots meurtriers.",
    "Une comédie de bureau qui se déroule dans un laboratoire high-tech et suit Ted, un directeur de projet.",
    "Après un accident, Jaime Sommers devient une femme bionique et doit utiliser ses nouvelles capacités pour lutter contre le crime.",
    "Blade, un chasseur de vampires, se bat pour éliminer les vampires qui menacent l'humanité.",
    "Une détective privée découvre un monde surnaturel tout en résolvant des crimes.",
    "Des enquêtes médico-légales passionnantes avec la brillante anthropologue judiciaire Temperance Brennan.",
    "Un professeur de chimie se tourne vers la fabrication de méthamphétamine pour subvenir aux besoins de sa famille.",
    "Buffy, la tueuse de vampires, combat les forces démoniaques à Sunnydale.",
    "Un espion renvoyé du gouvernement cherche à découvrir pourquoi il a été brûlé.",
    "La vie chaotique d'un écrivain à succès, Hank Moody, à Los Angeles.",
    "Cette préquelle de 'Battlestar Galactica' explore la création des Cylons et la montée des machines.",
    "Trois sœurs découvrent qu'elles sont des sorcières puissantes et luttent contre les forces du mal.",
    "Un employé d'une boutique électronique se retrouve avec des secrets gouvernementaux dans son cerveau.",
    "Une détective réexamine d'anciennes affaires non résolues pour résoudre des meurtres.",
    "Un groupe d'étudiants d'un collège communautaire vivent des aventures loufoques.",
    "Une équipe de profileurs du FBI traque des criminels dangereux.",
    "Un homme prétendant être Cupidon aide les gens à trouver l'amour dans cette comédie romantique.",
    "Un détective revit le même jour encore et encore tout en résolvant un complot meurtrier.",
    "Un jeune homme découvre qu'il est le descendant de Van Helsing et doit combattre les démons.",
    "La vie des femmes au foyer dans une banlieue apparemment parfaite est pleine de secrets et de drames.",
    "Dexter Morgan est un expert en médecine légale le jour, tueur en série la nuit.",
    "Un avocat devient le conseiller d'une famille riche et découvre leurs sombres secrets.",
    "Une série dramatique qui se déroule dans le monde du journalisme à scandale.",
    "Le Docteur voyage à travers le temps et l'espace dans cette série de science-fiction emblématique.",
    "Une organisation secrète contrôle des poupées humaines programmables pour diverses missions.",
    "Un scientifique enquête sur des phénomènes scientifiques et des catastrophes.",
    "La vie d'une star de cinéma hollywoodienne et de ses amis.",
    "Dans la ville d'Eureka, les meilleurs cerveaux du monde travaillent sur des inventions inhabituelles.",
    "Les mésaventures d'acteurs cherchant à réussir à Hollywood.",
    "Une série d'anthologie d'horreur explorant les peurs humaines.",
    "Après un blackout mondial, les gens ont des visions de leur avenir.",
    "Une unité d'élite de la police gère des situations de crise à haut risque.",
    "Une comédie musicale mettant en scène un groupe folk néo-zélandais à New York.",
    "Un drame sur le football lycéen au Texas et la vie des gens de la petite ville.",
    "Une comédie emblématique mettant en scène un groupe d'amis à New York.",
    "Une unité spéciale enquête sur des phénomènes mystérieux et des expériences scientifiques.",
    "Un livreur de pizza est accidentellement congelé et se réveille 1000 ans plus tard dans un monde futuriste délirant.",
    "Un homme divorcé navigue dans sa nouvelle vie de célibataire.",
    "Une femme peut communiquer avec les esprits et les aider à résoudre leurs problèmes non résolus.",
    "Une blogueuse anonyme raconte les secrets des élites de l'Upper East Side.",
    "La vie d'étudiants dans une fraternité grecque sur un campus universitaire.",
    "Un groupe de médecins dans un hôpital de Seattle navigue dans les complexités de la médecine et de la vie personnelle.",
    "Des individus découvrent qu'ils ont des super-pouvoirs et tentent de sauver le monde.",
    "Le Dr Gregory House résout des cas médicaux mystérieux tout en étant un homme excentrique.",
    "Un homme raconte à ses enfants comment il a rencontré leur mère, avec l'aide de ses amis.",
    "Un psychothérapeute traite les problèmes de ses patients tout en affrontant les siens.",
    "Une série de science-fiction sur une invasion extraterrestre et ses conséquences.",
    "Un employé de bureau devient un agent secret avec des pouvoirs améliorés.",
    "Une version moderne de l'histoire classique de Jekyll et Hyde.",
    "Une petite ville tente de survivre après une attaque nucléaire.",
    "Un étranger mystérieux arrive dans une ville côtière et change la vie des habitants.",
    "Un homme et sa voiture intelligente combattent le crime.",
    "Un adolescent sans nom et sans mémoire développe des pouvoirs surnaturels.",
    "Un guide doit trouver une pierre magique pour arrêter un tyran maléfique.",
    "Une équipe de cambrioleurs professionnels vole aux riches pour donner aux pauvres.",
    "Un expert en détection de mensonges lit les expressions faciales pour résoudre des enquêtes.",
    "Un détective retourne au travail après avoir été en prison et continue à résoudre des crimes.",
    "Les survivants d'un crash d'avion tentent de survivre sur une île mystérieuse.",
    "La vie des publicitaires dans les années 1960 à New York.",
    "Une anthologie de science-fiction avec différentes histoires à chaque épisode.",
    "Une femme peut communiquer avec les morts et les aide à résoudre des affaires criminelles.",
    "La vie des habitants d'un immeuble d'appartements de Los Angeles.",
    "Un psychiatre dirige une unité de psychiatrie criminelle dans un hôpital.",
    "L'histoire du magicien Merlin à une époque où la magie est interdite.",
    "Un vampire détective privé résout des crimes à Los Angeles.",
    "Un homme fait une liste de bonnes actions après avoir gagné à la loterie.",
    "Une équipe d'enquêteurs du NCIS résout des crimes à Los Angeles.",
    "Une équipe d'enquêteurs du NCIS résout des crimes impliquant la marine américaine.",
    "Deux chirurgiens plasticiens gèrent une clinique à Miami.",
    "La vie des habitants de la ville fictive de Tree Hill.",
    "La vie des détenus dans une prison expérimentale.",
    "Une femme dotée de la capacité de guérison lutte contre des menaces biologiques.",
    "Des anomalies temporelles permettent à des créatures préhistoriques d'envahir le monde.",
    "Un homme se fait délibérément incarcérer pour aider son frère à s'échapper de prison.",
    "Les médecins d'une clinique privée traitent des cas médicaux et personnels.",
    "Un détective prétend avoir des pouvoirs psychiques pour résoudre des crimes.",
    "Un homme peut ramener les morts à la vie, mais avec des conséquences.",
    "Un détective voit et parle avec les victimes de meurtres.",
    "Un homme devient un chasseur de démons pour le diable.",
    "L'histoire classique de Robin des Bois et de ses compagnons.",
    "Une femme amnésique découvre qu'elle n'était pas une bonne personne.",
    "Une équipe traque des créatures surnaturelles dans un sanctuaire secret.",
    "Les médecins et le personnel d'un hôpital enseignent des leçons de vie tout en pratiquant la médecine.",
    "Quatre amies vivent des aventures amoureuses et professionnelles à New York.",
    "Une famille gère une entreprise de pompes funèbres tout en faisant face à des problèmes personnels.",
    "La vie de jeunes adolescents britanniques.",
    "L'adolescence de Clark Kent, alias Superman.",
    "Un gang de motards criminalistes opère en Californie.",
    "Les aventures hilarantes de quatre garçons dans une petite ville du Colorado.",
    "Deux amis prétendent être un couple pour louer un appartement.",
    "Une équipe explore une cité perdue dans une autre galaxie.",
    "Une équipe militaire voyage à travers des portes stellaires pour protéger la Terre.",
    "Une équipe se retrouve à bord d'un vaisseau spatial ancien et mystérieux.",
    "Deux frères chassent des créatures surnaturelles.",
    "La vie d'un couple marié qui explore l'échangisme dans les années 1970.",
    "Des personnes disparues réapparaissent avec des pouvoirs surnaturels.",
    "Des scientifiques socialement maladroits vivent des aventures comiques.",
    "Quatre frères irlandais sont impliqués dans des activités criminelles à New York.",
    "Un groupe de vétérans de la guerre en Irak tente de voler une banque.",
    "Un détective trouve des objets avec des pouvoirs mystérieux.",
    "Un enquêteur utilise ses talents de lecture pour résoudre des crimes.",
    "Neuf étrangers sont pris en otage dans une banque et doivent faire face à des conséquences durables.",
    "La vie d'un adolescent dans un quartier riche de la Californie.",
    "Un homme avec une intelligence surhumaine traque des fugitifs.",
    "Une famille de gitans escroque des familles riches.",
    "La mère de John Connor combat des robots tueurs du futur.",
    "Des policiers corrompus luttent contre le crime à Los Angeles.",
    "La vie d'un chef de la mafia du New Jersey.",
    "Les règnes de Henri VIII d'Angleterre et ses nombreuses femmes.",
    "Une adolescente découvre qu'elle est amoureuse d'un vampire.",
    "La vie à Baltimore, entre la police et le trafic de drogue.",
    "Une équipe traque des menaces extraterrestres à Cardiff.",
    "Deux amis sont accusés à tort de terrorisme et fuient pour prouver leur innocence.",
    "Une femme peut revivre la même journée pour empêcher des décès.",
    "Les vampires vivent ouvertement parmi les humains, créant des conflits.",
    "Une jeune femme travaille dans le monde de la mode tout en restant elle-même.",
    "Une adolescente résout des mystères à Neptune, en Californie.",
    "Des extraterrestres pacifiques se révèlent être une menace pour la Terre.",
    "Une veuve vend de la marijuana pour subvenir aux besoins de sa famille.",
    "Une équipe de police résout des crimes inspirés d'événements historiques.",
    "Quatre femmes enquêtent sur des meurtres à San Francisco.",
    "Des agents du FBI enquêtent sur des phénomènes paranormaux et extraterrestres.",
    "La chute de la République romaine et la montée de l'Empire."
]

# Requête SQL d'insertion
insert_query = text("INSERT INTO serie (description) VALUES (:description)")

# Boucle pour insérer les descriptions pour chaque série
for i in range(len(noms_series)):
    nom_serie = noms_series[i]
    description = descriptions[i]

    # Exécutez la requête d'insertion avec les paramètres
    session.execute(insert_query, {"nom_serie": nom_serie, "description": description})

# Appliquez les modifications à la base de données
session.commit()

# Fermez la session
session.close()