import re
from sqlalchemy import create_engine, text

# Configuration de la connexion à la base de données MySQL
db_username = 'root'
db_password = ''
db_host = 'localhost'
db_port = '3306'
db_name = 'projet_sae'

# Créez un moteur SQLAlchemy
engine = create_engine(f'mysql+mysqlconnector://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}', echo=True)

# Liste des catégories
series_categories = [
    ("24", "Action"),
    ("90210", "Drame"),
    ("Alias", "Action"),
    ("Angel", "Drame"),
    ("Battlestar Galactica", "Science-fiction"),
    ("Better Off Ted", "Comédie"),
    ("Bionic Woman", "Action"),
    ("Blade", "Action"),
    ("Blood Ties", "Drame"),
    ("Bones", "Drame"),
    ("Breaking Bad", "Drame"),
    ("Buffy", "Drame"),
    ("Burn Notice", "Action"),
    ("Californication", "Comédie"),
    ("Caprica", "Science-fiction"),
    ("Charmed", "Drame"),
    ("Chuck", "Action"),
    ("Cold Case", "Drame"),
    ("Community", "Comédie"),
    ("Criminal Minds", "Drame"),
    ("Cupid", "Comédie"),
    ("Day Break", "Drame"),
    ("Demons", "Action"),
    ("Desperate Housewives", "Drame"),
    ("Dexter", "Drame"),
    ("Dirty Sexy Money", "Drame"),
    ("Dirt", "Drame"),
    ("Doctor Who", "Science-fiction"),
    ("Dollhouse", "Science-fiction"),
    ("Eleventh Hour", "Drame"),
    ("Entourage", "Comédie"),
    ("Eureka", "Science-fiction"),
    ("Extras", "Comédie"),
    ("Fear Itself", "Horreur"),
    ("FlashForward", "Drame"),
    ("Flashpoint", "Drame"),
    ("Flight of the Conchords", "Comédie"),
    ("Friday Night Lights", "Drame"),
    ("Friends", "Comédie"),
    ("Fringe", "Science-fiction"),
    ("Futurama", "Comédie"),
    ("Gary Unmarried", "Comédie"),
    ("Ghost Whisperer", "Drame"),
    ("Gossip Girl", "Drame"),
    ("Greek", "Comédie"),
    ("Grey's Anatomy", "Drame"),
    ("Heroes", "Drame"),
    ("House", "Drame"),
    ("How I Met Your Mother", "Comédie"),
    ("In Treatment", "Drame"),
    ("Invasion", "Science-fiction"),
    ("Jake 2.0", "Science-fiction"),
    ("Jekyll", "Drame"),
    ("Jericho", "Drame"),
    ("John from Cincinnati", "Drame"),
    ("Knight Rider", "Action"),
    ("Kyle XY", "Science-fiction"),
    ("Legend of the Seeker", "Action"),
    ("Leverage", "Action"),
    ("Lie to Me", "Drame"),
    ("Life", "Drame"),
    ("Lost", "Drame"),
    ("Mad Men", "Drame"),
    ("Masters of SciFi", "Science-fiction"),
    ("Medium", "Drame"),
    ("Melrose Place", "Drame"),
    ("Mental", "Drame"),
    ("Merlin", "Drame"),
    ("Moonlight", "Drame"),
    ("My Name Is Earl", "Comédie"),
    ("NCIS: Los Angeles", "Drame"),
    ("NCIS", "Drame"),
    ("Nip/Tuck", "Drame"),
    ("One Tree Hill", "Drame"),
    ("Oz", "Drame"),
    ("Painkiller Jane", "Action"),
    ("Primeval", "Science-fiction"),
    ("Prison Break", "Drame"),
    ("Private Practice", "Drame"),
    ("Psych", "Comédie"),
    ("Pushing Daisies", "Comédie"),
    ("Raines", "Drame"),
    ("Reaper", "Comédie"),
    ("Robin Hood", "Action"),
    ("Samantha Who?", "Comédie"),
    ("Sanctuary", "Science-fiction"),
    ("Scrubs", "Comédie"),
    ("Sex and the City", "Comédie"),
    ("Six Feet Under", "Drame"),
    ("Skins", "Drame"),
     ("Smallville", "Drame"),
    ("Sons of Anarchy", "Drame"),
    ("South Park", "Comédie"),
    ("Spaced", "Comédie"),
    ("Stargate Atlantis", "Science-fiction"),
    ("Stargate SG-1", "Science-fiction"),
    ("Stargate Universe", "Science-fiction"),
    ("Supernatural", "Drame"),
    ("Swingtown", "Drame"),
    ("The 4400", "Science-fiction"),
    ("The Big Bang Theory", "Comédie"),
    ("The Black Donnellys", "Drame"),
    ("The Kill Point", "Drame"),
    ("The Lost Room", "Drame"),
    ("The Mentalist", "Drame"),
    ("The Nine", "Drame"),
    ("The OC", "Drame"),
    ("The Pretender", "Drame"),
    ("The Riches", "Drame"),
    ("The Sarah Connor Chronicles", "Science-fiction"),
    ("The Shield", "Drame"),
    ("The Sopranos", "Drame"),
    ("The Tudors", "Drame"),
    ("The Vampire Diaries", "Drame"),
    ("The Wire", "Drame"),
    ("Torchwood", "Science-fiction"),
    ("Traveler", "Drame"),
    ("Tru Calling", "Drame"),
    ("True Blood", "Drame"),
    ("Ugly Betty", "Comédie"),
    ("Veronica Mars", "Drame"),
    ("V", "Science-fiction"),
    ("Weeds", "Comédie"),
    ("Whitechapel", "Drame"),
    ("Women's Murder Club", "Drame"),
    ("The X-Files", "Drame"),
    ("Rome", "Drame")
]

series_formatees = [re.sub(r'[^a-zA-Z0-9]', '', serie).lower() for serie, _ in series_categories]

# Mise à jour des catégories des séries
with engine.connect() as conn:
    for (serie, categorie), serie_formattee in zip(series_categories, series_formatees):
        update_query = text("UPDATE serie SET categorie = :categorie WHERE titre = :titre")
        conn.execute(update_query, {"titre": serie_formattee, "categorie": categorie})
        conn.commit()